openapi: 3.0.0
info:
  title: Turkish Recipe API
  description: Simple REST API for Turkish recipes
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server

tags:
  - name: Recipes
    description: Recipe endpoints
  - name: Categories
    description: Category endpoints

paths:
  /api/recipes:
    get:
      tags:
        - Recipes
      summary: Get all recipes
      description: Returns all recipes or filtered by category
      parameters:
        - in: query
          name: categoryId
          schema:
            type: string
          description: Filter by category ID (e.g., main-course, dessert)
          example: main-course
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RecipeListItem'
                  total:
                    type: integer
                    example: 10

  /api/recipes/{id}:
    get:
      tags:
        - Recipes
      summary: Get recipe by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Recipe ID
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Recipe'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/categories:
    get:
      tags:
        - Categories
      summary: Get all categories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
                  total:
                    type: integer
                    example: 8

  /api/categories/{id}:
    get:
      tags:
        - Categories
      summary: Get category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Category ID
          example: main-course
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Category'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          example: main-course
        name:
          type: string
          example: Main Dishes
        description:
          type: string
          example: Traditional Turkish main dishes

    Recipe:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Karn覺yar覺k
        description:
          type: string
          example: Traditional Turkish eggplant dish
        categoryId:
          type: string
          example: main-course
        difficulty:
          type: string
          enum: [Easy, Medium, Hard]
        prepTime:
          type: integer
          description: Minutes
          example: 30
        cookTime:
          type: integer
          description: Minutes
          example: 45
        servings:
          type: integer
          example: 4
        calories:
          type: integer
          example: 320
        image:
          type: string
          example: https://example.com/images/karniyarik.jpg
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        instructions:
          type: array
          items:
            type: string
        nutrition:
          $ref: '#/components/schemas/Nutrition'

    RecipeListItem:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Karn覺yar覺k
        description:
          type: string
          example: Traditional Turkish eggplant dish
        categoryId:
          type: string
          example: main-course
        category:
          type: string
          example: Main Dishes
        difficulty:
          type: string
          enum: [Easy, Medium, Hard]
        prepTime:
          type: integer
          example: 30
        cookTime:
          type: integer
          example: 45
        image:
          type: string
          example: https://example.com/images/karniyarik.jpg

    Ingredient:
      type: object
      properties:
        name:
          type: string
          example: eggplant
        amount:
          type: number
          example: 4
        unit:
          type: string
          example: piece

    Nutrition:
      type: object
      properties:
        calories:
          type: integer
          example: 320
        protein:
          type: integer
          example: 18
        carbohydrates:
          type: integer
          example: 24
        fat:
          type: integer
          example: 15
        fiber:
          type: integer
          example: 8

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not found